units:
  # Proxy Spacing Variables
  kx: cx
  ky: cy

  # Padding Variables
  px: kx + 7
  py: ky + 7

  # 8 padding
  ppx: kx + 8
  ppy: ky + 8

  # --- Microcontroller pad params
  mcu_w: 40 # pad width
  mcu_h: 80 # pad height
  mcu_dx: px * .85 # how far to shove the pad to the right from inner_home

  # M2
  screwSize: 1.5
  standoffSize: 2.5

points:
  zones:
    main:
      anchor:
        shift: [100, -100]
      key:
        padding: 1ky
        spread: 1kx
      columns:
        outer:
          key.column_net: P21
          rows.mod.skip: true
        pinky:
          key.column_net: P20
          rows.mod.skip: true
        ring:
          key.column_net: P19
          key.stagger: 4
        middle:
          key.column_net: P18
          key.stagger: 2.5
        index:
          key.column_net: P15
          key.stagger: -2.5
        inner:
          key.column_net: P14
          key.stagger: -2.5
          rows.mod.skip: true
      rows:
        mod:
          row_net: P8
        bottom:
          row_net: P7
        home:
          row_net: P6
        top:
          row_net: P5
        num:
          row_net: P4

    thumb:
      key:
        padding: 1ky
        spread: 1kx
      anchor:
        ref: main_inner_mod
        shift: [2, -2]
      columns:
        layer:
          key:
            column_net: P16
            splay: -30
            shift: [2, -2]
        space:
          key:
            column_net: P10
            splay: -15
            shift: [5, -5]
        extra:
          key:
            column_net: P9
            splay: -15
            shift: [8.7, -6]
      rows:
        cluster:
          row_net: P4

  mirror:
    ref: main_inner_num
    distance: 100

outlines:
  left_raw:
    - what: rectangle
      where: "meta.name ~ /^(?!mirror_).*/"
      size: [px, py]
    - what: rectangle
      where:
        ref: main_inner_home
        shift: [mcu_dx, 0]
      size: [mcu_w, mcu_h]

  right_raw:
    - what: rectangle
      where: "meta.name ~ /^mirror_.*/"
      size: [px, py]
    - what: rectangle
      where:
        ref: mirror_main_inner_home
        shift: [mcu_dx, 0]
      size: [mcu_w, mcu_h]

  left_keys:
    - what: rectangle
      where: "meta.name ~ /^(?!mirror_).*/"
      bound: false
      size: [kx - 0.5, ky - 0.5]

  right_keys:
    - what: rectangle
      where: "meta.name ~ /^mirror_.*/"
      bound: false
      size: [kx - 0.5, ky - 0.5]

  combo_left:
    - name: left_raw
    - operation: subtract
      name: left_keys

  combo_right:
    - name: right_raw
    - operation: subtract
      name: right_keys

  left_xl:
    - what: outline
      name: left_raw
      expand: 2
      fillet: 2

  right_xl:
    - what: outline
      name: right_raw
      expand: 2
      fillet: 2

  left_mounting:
    - what: circle
      radius: screwSize
      where:
        ref: [main_outer_num]
        shift: [-8, 8]
    - what: circle
      radius: screwSize
      where:
        ref: [main_outer_bottom]
        shift: [-8, -8]
    - what: circle
      radius: screwSize
      where:
        ref: [main_inner_bottom]
        shift: [22, -13]
    - what: circle
      radius: screwSize
      where:
        ref: [main_inner_bottom]
        shift: [22, 13]
    - what: circle
      radius: screwSize
      where:
        ref: [main_inner_bottom]
        shift: [22, 38]

  right_mounting:
    - what: circle
      radius: screwSize
      where:
        ref: [mirror_main_outer_num]
        shift: [-8, 8]
    - what: circle
      radius: screwSize
      where:
        ref: [mirror_main_outer_bottom]
        shift: [-8, -8]
    - what: circle
      radius: screwSize
      where:
        ref: [mirror_main_inner_bottom]
        shift: [22, -13]
    - what: circle
      radius: screwSize
      where:
        ref: [mirror_main_inner_bottom]
        shift: [22, 13]
    - what: circle
      radius: screwSize
      where:
        ref: [mirror_main_inner_bottom]
        shift: [22, 38]

  left_standoff:
    - what: circle
      radius: standoffSize
      where:
        ref: [main_outer_num]
        shift: [-8, 8]
    - what: circle
      radius: standoffSize
      where:
        ref: [main_outer_bottom]
        shift: [-8, -8]
    - what: circle
      radius: standoffSize
      where:
        ref: [main_inner_bottom]
        shift: [22, -13]
    - what: circle
      radius: standoffSize
      where:
        ref: [main_inner_bottom]
        shift: [22, 13]
    - what: circle
      radius: standoffSize
      where:
        ref: [main_inner_bottom]
        shift: [22, 38]

  right_standoff:
    - what: circle
      radius: standoffSize
      where:
        ref: [mirror_main_outer_num]
        shift: [-8, 8]
    - what: circle
      radius: standoffSize
      where:
        ref: [mirror_main_outer_bottom]
        shift: [-8, -8]
    - what: circle
      radius: standoffSize
      where:
        ref: [mirror_main_inner_bottom]
        shift: [22, -13]
    - what: circle
      radius: standoffSize
      where:
        ref: [mirror_main_inner_bottom]
        shift: [22, 13]
    - what: circle
      radius: standoffSize
      where:
        ref: [mirror_main_inner_bottom]
        shift: [22, 38]

pcbs:
  left_board:
    template: kicad8
    outlines:
      - outline: left_raw
    footprints:
      chod_hotswap:
        what: choc
        where: "meta.name ~ /^(?!mirror_).*/"
        asym: source
        params:
          keycaps: true
          reverse: false
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"

      diode:
        what: diode
        where: "meta.name ~ /^(?!mirror_).*/"
        asym: source
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, -5]

      promicro:
        what: promicro
        params:
          orientation: "up"
        where:
          ref: main_inner_home
          shift: [mcu_dx, 20.5]
          rotate: -90

      oled:
        what: oled
        params:
          side: "F"
          SDA: P2
          SCL: P3
          VCC: VCC
          GND: GND
        where:
          ref: main_inner_top
          shift: [mcu_dx + 6, -15]
          rotate: -90

      reset:
        what: button
        params:
          from: GND
          to: RST
        where:
          ref: main_inner_top
          shift: [mcu_dx + 14, -12]
          rotate: -90

      trrs:
        what: trrs
        params:
          reverse: false
          symmetric: true
          A: VCC
          B: GND
          C: GND
          D: P0
        where:
          ref: main_inner_top
          shift: [mcu_dx + 16.5, 21]
          rotate: 0

      esd_data:
        what: diode
        params:
          from: P0
          to: GND
        where:
          ref: main_inner_top
          shift: [mcu_dx + 16.5, 3]
          rotate: 90

      esd_vcc:
        what: diode
        params:
          from: VCC
          to: GND
        where:
          ref: main_inner_top
          shift: [mcu_dx + 12.5, 3]
          rotate: 90

      hole_top_left:
        what: mounting_hole_npth
        where:
          ref: main_outer_num
          shift: [-8, 8]

      hole_bottom_left:
        what: mounting_hole_npth
        where:
          ref: main_outer_bottom
          shift: [-8, -8]

      hole_bottom_right:
        what: mounting_hole_npth
        where:
          ref: main_inner_bottom
          shift: [22, -13]

      hole_middle_right:
        what: mounting_hole_npth
        where:
          ref: main_inner_bottom
          shift: [22, 13]

      hole_top_right:
        what: mounting_hole_npth
        where:
          ref: main_inner_bottom
          shift: [21, 38]

  right_board:
    template: kicad8
    outlines:
      - outline: right_raw
    footprints:
      chod_hotswap:
        what: choc
        where: "meta.name ~ /^mirror_.*/"
        asym: source
        params:
          keycaps: true
          reverse: false
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"

      diode:
        what: diode
        where: "meta.name ~ /^mirror_.*/"
        asym: source
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, -5]

      promicro:
        what: promicro
        params:
          orientation: "up"
        where:
          ref: mirror_main_inner_home
          shift: [mcu_dx, 20.5]
          rotate: 90

      oled:
        what: oled
        params:
          side: "F"
          SDA: P2
          SCL: P3
          VCC: VCC
          GND: GND
        where:
          ref: mirror_main_inner_top
          shift: [mcu_dx + 6, -18]
          rotate: -90

      reset:
        what: button
        params:
          from: GND
          to: RST
        where:
          ref: mirror_main_inner_top
          shift: [mcu_dx + 14, -12]
          rotate: -90

      trrs:
        what: trrs
        params:
          reverse: false
          symmetric: true
          A: VCC
          B: GND
          C: GND
          D: P0
        where:
          ref: mirror_main_inner_top
          shift: [mcu_dx + 12.5, 21]
          rotate: 0

      esd_data:
        what: diode
        params:
          from: P0
          to: GND
        where:
          ref: mirror_main_inner_top
          shift: [mcu_dx + 12.5, 3]
          rotate: 90

      esd_vcc:
        what: diode
        params:
          from: VCC
          to: GND
        where:
          ref: mirror_main_inner_top
          shift: [mcu_dx + 16.5, 3]
          rotate: 90

      hole_top_left:
        what: mounting_hole_npth
        where:
          ref: mirror_main_outer_num
          shift: [-8, 8]

      hole_bottom_left:
        what: mounting_hole_npth
        where:
          ref: mirror_main_outer_bottom
          shift: [-8, -8]

      hole_bottom_right:
        what: mounting_hole_npth
        where:
          ref: mirror_main_inner_bottom
          shift: [22, -13]

      hole_middle_right:
        what: mounting_hole_npth
        where:
          ref: mirror_main_inner_bottom
          shift: [22, 13]

      hole_top_right:
        what: mounting_hole_npth
        where:
          ref: mirror_main_inner_bottom
          shift: [21, 38]

cases:
  left_bottom:
    - name: left_raw
      extrude: 1

  xl_left_bottom:
    - name: left_xl
      extrude: 1

  _left_outer_wall:
    - name: left_xl
      extrude: 5.6

  _left_inner_wall:
    - name: left_raw
      extrude: 5.6

  _left_holes:
    - name: left_mounting
      extrude: 4

  _left_standoffs:
    - name: left_standoff
      extrude: 4

  left_wall:
    - what: case
      name: _left_outer_wall
      operation: add
    - what: case
      name: _left_inner_wall
      operation: subtract

  left_case:
    - what: case
      name: xl_left_bottom
      operation: add
    - what: case
      name: _left_standoffs
      operation: add
    - what: case
      name: _left_holes
      operation: subtract
    - what: case
      name: left_wall
      operation: add

  right_bottom:
    - name: right_raw
      extrude: 1

  xl_right_bottom:
    - name: right_xl
      extrude: 1

  _right_outer_wall:
    - name: right_xl
      extrude: 5.6

  _right_inner_wall:
    - name: right_raw
      extrude: 5.6

  _right_holes:
    - name: right_mounting
      extrude: 4

  _right_standoffs:
    - name: right_standoff
      extrude: 4

  right_wall:
    - what: case
      name: _right_outer_wall
      operation: add
    - what: case
      name: _right_inner_wall
      operation: subtract

  right_case:
    - what: case
      name: xl_right_bottom
      operation: add
    - what: case
      name: _right_standoffs
      operation: add
    - what: case
      name: _right_holes
      operation: subtract
    - what: case
      name: right_wall
      operation: add
